CREATE DATABASE GAMEDOAN;
USE GAMEDOAN;
CREATE USER [AcountForGame] FOR LOGIN [AcountForGame];
ALTER ROLE db_owner ADD MEMBER [AcountForGame];

CREATE TABLE USERS (
    UserID INT IDENTITY PRIMARY KEY,
    UserName NVARCHAR(50) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(255) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE()
);
CREATE TABLE HIGHSCORES (
    ScoreID INT IDENTITY PRIMARY KEY,
    UserID INT NOT NULL,
    ScoreValue INT NOT NULL,
    AchievedAt DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (UserID) REFERENCES USERS(UserID)
);
CREATE TABLE PLAYHISTORY (
    HistoryID INT IDENTITY PRIMARY KEY,
    UserID INT NOT NULL,
    Score INT NOT NULL,
    Duration INT,
    PlayDate DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (UserID) REFERENCES USERS(UserID)
);
CREATE TABLE SAVEDGAME (
    SaveID INT IDENTITY PRIMARY KEY,
    UserID INT NOT NULL UNIQUE,
    BoardState NVARCHAR(MAX),
    CurrentPiece NVARCHAR(MAX),
    NextPiece NVARCHAR(MAX),
    Score INT,
    Level INT,
    SaveDate DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (UserID) REFERENCES USERS(UserID)
);
SELECT * FROM USERS